recipes.remove(<projectred-expansion:machine2:*>);
recipes.remove(<enderio:block_farm_station:*>);
recipes.remove(<enderio:block_tank:*>);
recipes.remove(<enderio:item_dark_steel_hand>);
recipes.remove(<enderio:block_combustion_generator>);
recipes.remove(<enderio:block_enhanced_combustion_generator>);
recipes.remove(<enderio:block_lava_generator>);
recipes.remove(<enderio:item_soul_vial:*>);
recipes.remove(<enderio:block_vacuum_chest:*>);
recipes.remove(<enderio:block_simple_crafter>);
recipes.remove(<enderio:block_crafter>);
recipes.remove(<enderio:block_simple_furnace>);
recipes.remove(<enderio:block_simple_stirling_generator>);
recipes.remove(<enderio:block_stirling_generator>);

/* 
recipes.remove(<enderio:block_simple_alloy_smelter:*>);
recipes.remove(<enderio:block_enhanced_alloy_smelter:*>);
recipes.remove(<enderio:block_alloy_smelter:*>);
recipes.remove(<enderio:block_cap_bank:*>);
recipes.remove(<enderio:block_solar_panel:*>);
*/